[package]
name = "zone-detect"
version = "0.2.0"
authors = ["Nicholas Bishop <nicholasbishop@gmail.com>"]
edition = "2018"
license = "BSD-3-Clause"
repository = "https://github.com/nicholasbishop/zone-detect-rs"
description = "Rust version of the ZoneDetect C library."
keywords = ["time", "zone", "timezone"]

[dependencies]
thiserror = { version = "1.0.29", default_features = false }

[dev-dependencies]
clap = { version = "2.33.3", default_features = false }
rand = { version = "0.8.4", default_features = false }
structopt = { version = "0.3.23", default_features = false }
