[package]
name = "tzlookup"
version = "0.1.0"
authors = ["Nicholas Bishop <nicholasbishop@gmail.com>"]
edition = "2018"

[dependencies]
libc = "0.2"
thiserror = "1.0"

[dev-dependencies]
rand = "0.7"
