//! Unsafe wrapper for the ZoneDetect C library generated by bindgen.

#![allow(clippy::unreadable_literal)]
#![allow(missing_docs)]
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
